name: Oracle ARM Hunter

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # 30 dakikada bir otomatik çalışır

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # En güncel checkout sürümü

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Güncel PHP sürümü

      - name: Install Dependencies
        run: composer install --no-dev # Gereksiz paketleri yüklemez

      - name: Run Script
        run: php index.php
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          # Burası kritik: DOSYA yerine METİN içeriği olarak gönderiyoruz
          OCI_PRIVATE_KEY_CONTENTS: ${{ secrets.OCI_PRIVATE_KEY }} 
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          OCI_OCPUS: 4
          OCI_MEMORY_IN_GBS: 24
          OCI_MAX_INSTANCES: 1
