name: Oracle ARM Hunter

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install Dependencies
        run: composer install --no-dev

      - name: Create Private Key File
        run: |
          echo "${{ secrets.OCI_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Run Script
        run: php index.php
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_OCID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_OCID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME: ./private_key.pem
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          OCI_AVAILABILITY_DOMAIN: ${{ secrets.OCI_AVAILABILITY_DOMAIN }}
          # Burası çok önemli, az önce hata aldığın secret'ı buraya bağladık:
          OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
          OCI_SHAPE: VM.Standard.A1.Flex
          OCI_OCPUS: 4
          OCI_MEMORY_IN_GBS: 24
          OCI_MAX_INSTANCES: 1
